//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC.SrvUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/MudanzasGuaymasServices.Entity")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvUsuario.ISrvUsuario")]
    public interface ISrvUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/Insertar", ReplyAction="http://tempuri.org/ISrvUsuario/InsertarResponse")]
        bool Insertar(TestMVC.SrvUsuario.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/Insertar", ReplyAction="http://tempuri.org/ISrvUsuario/InsertarResponse")]
        System.Threading.Tasks.Task<bool> InsertarAsync(TestMVC.SrvUsuario.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/Editar", ReplyAction="http://tempuri.org/ISrvUsuario/EditarResponse")]
        void Editar(TestMVC.SrvUsuario.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/Editar", ReplyAction="http://tempuri.org/ISrvUsuario/EditarResponse")]
        System.Threading.Tasks.Task EditarAsync(TestMVC.SrvUsuario.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/Eliminar", ReplyAction="http://tempuri.org/ISrvUsuario/EliminarResponse")]
        bool Eliminar(TestMVC.SrvUsuario.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/Eliminar", ReplyAction="http://tempuri.org/ISrvUsuario/EliminarResponse")]
        System.Threading.Tasks.Task<bool> EliminarAsync(TestMVC.SrvUsuario.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/ConsultarTodos", ReplyAction="http://tempuri.org/ISrvUsuario/ConsultarTodosResponse")]
        TestMVC.SrvUsuario.Usuario[] ConsultarTodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/ConsultarTodos", ReplyAction="http://tempuri.org/ISrvUsuario/ConsultarTodosResponse")]
        System.Threading.Tasks.Task<TestMVC.SrvUsuario.Usuario[]> ConsultarTodosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/ConsultarPorNombre", ReplyAction="http://tempuri.org/ISrvUsuario/ConsultarPorNombreResponse")]
        TestMVC.SrvUsuario.Usuario[] ConsultarPorNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/ConsultarPorNombre", ReplyAction="http://tempuri.org/ISrvUsuario/ConsultarPorNombreResponse")]
        System.Threading.Tasks.Task<TestMVC.SrvUsuario.Usuario[]> ConsultarPorNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/ConsultarPorId", ReplyAction="http://tempuri.org/ISrvUsuario/ConsultarPorIdResponse")]
        TestMVC.SrvUsuario.Usuario ConsultarPorId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvUsuario/ConsultarPorId", ReplyAction="http://tempuri.org/ISrvUsuario/ConsultarPorIdResponse")]
        System.Threading.Tasks.Task<TestMVC.SrvUsuario.Usuario> ConsultarPorIdAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISrvUsuarioChannel : TestMVC.SrvUsuario.ISrvUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SrvUsuarioClient : System.ServiceModel.ClientBase<TestMVC.SrvUsuario.ISrvUsuario>, TestMVC.SrvUsuario.ISrvUsuario {
        
        public SrvUsuarioClient() {
        }
        
        public SrvUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SrvUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Insertar(TestMVC.SrvUsuario.Usuario usuario) {
            return base.Channel.Insertar(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAsync(TestMVC.SrvUsuario.Usuario usuario) {
            return base.Channel.InsertarAsync(usuario);
        }
        
        public void Editar(TestMVC.SrvUsuario.Usuario usuario) {
            base.Channel.Editar(usuario);
        }
        
        public System.Threading.Tasks.Task EditarAsync(TestMVC.SrvUsuario.Usuario usuario) {
            return base.Channel.EditarAsync(usuario);
        }
        
        public bool Eliminar(TestMVC.SrvUsuario.Usuario usuario) {
            return base.Channel.Eliminar(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(TestMVC.SrvUsuario.Usuario usuario) {
            return base.Channel.EliminarAsync(usuario);
        }
        
        public TestMVC.SrvUsuario.Usuario[] ConsultarTodos() {
            return base.Channel.ConsultarTodos();
        }
        
        public System.Threading.Tasks.Task<TestMVC.SrvUsuario.Usuario[]> ConsultarTodosAsync() {
            return base.Channel.ConsultarTodosAsync();
        }
        
        public TestMVC.SrvUsuario.Usuario[] ConsultarPorNombre(string nombre) {
            return base.Channel.ConsultarPorNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<TestMVC.SrvUsuario.Usuario[]> ConsultarPorNombreAsync(string nombre) {
            return base.Channel.ConsultarPorNombreAsync(nombre);
        }
        
        public TestMVC.SrvUsuario.Usuario ConsultarPorId(string id) {
            return base.Channel.ConsultarPorId(id);
        }
        
        public System.Threading.Tasks.Task<TestMVC.SrvUsuario.Usuario> ConsultarPorIdAsync(string id) {
            return base.Channel.ConsultarPorIdAsync(id);
        }
    }
}
